#! /bin/bash
#
# This script is meant to evoke th QA algorithm without requiring any input arguments
#
#

# Built to flywheel-v0 spec.
FLYWHEEL_BASE=/flywheel/v0
CONTAINER="[scitran/qa-dtiprep]"

# Configure the ENV
chmod +x /etc/fsl/5.0/fsl.sh
source /etc/fsl/5.0/fsl.sh
export PATH=$PATH:/opt/DTIPrepPackage

# Make sure that /output directory is empty (all content will be removed later).
OUTPUT_DIR=$FLYWHEEL_BASE/output
INPUT_DIR=$FLYWHEEL_BASE/input
INPUT_NIFTI=$INPUT_DIR/nifti
INPUT_BVEC=$INPUT_DIR/bvec
INPUT_BVAL=$INPUT_DIR/bval


if [ "-d" "$OUTPUT_DIR" ]
    then
        if [ "$(ls -A $OUTPUT_DIR)" ]; then
            echo -e "$OUTPUT_DIR is not Empty! Please provide an empty directory and mount at '$OUTPUT_DIR'."
            exit 1
        fi
    else
        echo "$OUTPUT_DIR not found. It will be created."
        mkdir $OUTPUT_DIR
fi


# Check if the inputs are empty.
# If so, show example usage and prompt for help
if [[ -z $@ ]]
    then
      dwi_nifti=`find $INPUT_NIFTI -type f -name "*.nii*" | head -1`
      dwi_bvec=`find $INPUT_BVEC -type f -name "*.bvec*" | head -1`
      dwi_bval=`find $INPUT_BVAL -type f -name "*.bval*" | head -1`
      if [[ -n $dwi_nifti ]]
        then
            echo -e "$CONTAINER  Starting DTIPrep..."
            $FLYWHEEL_BASE/qa-dtiprep.py --nifti "$dwi_nifti" --bval "$dwi_bval" --bvec "$dwi_bvec" 2>&1 | tee $OUTPUT_DIR/dtiprep_log.txt
      else
            echo "No inputs were provided and $INPUT_DIR has no valid input files!"
            exit 1
      fi
else
    $FLYWHEEL_BASE/qa-dtiprep.py $@
fi


# Get a list of the files in the output directory
find $OUTPUT_DIR -type f -name "*.nrrd" -exec rm {} \;

outputs=`find $OUTPUT_DIR -type f`


# If outputs exist, then go on...
if [[ -z $outputs ]]; then
    echo "No results found in output directory... Exiting(1)"
        exit 1
    else
        chmod -R 777 $OUTPUT_DIR

    $FLYWHEEL_BASE/metadata_create.py $OUTPUT_DIR $CONTAINER
    echo -e "$CONTAINER  Success!"
fi

exit 0
